name: Daily Deploy

env:
    DATA_URL: https://alias-db.minecraftpeayer.com/api/get/
    ARCADE_LIST_URL: https://alias-db.minecraftpeayer.com/arcades.json

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch: {}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        container:
            image: node:22
        concurrency:
            group: daily-deploy
            cancel-in-progress: true
        steps:
            -   name: checkout
                uses: actions/checkout@v4

            -   name: Deploy
                run: |
                    npm i
                    node script.js
                env:
                    DATA_URL: ${{ env.DATA_URL }}
                    ARCADE_LIST_URL: ${{ env.ARCADE_LIST_URL }}
            -   name: Deploy to GitHub Pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./dist
            
